version: "3.9"

networks:
  hackathon-network:
    driver: bridge

services:
  hackathon-api:
    container_name: hackathon-api
    build:
      context: ./backend
    image: hackathon-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT:-80}:8000"
    networks:
      - hackathon-network
    depends_on:
      hackathon-postgres:
        condition: service_healthy
    volumes:
      - ./backend/app:/app
      - ./volumes/${UPLOADED_FILES_DIRECTORY:-files}:/app/${UPLOADED_FILES_DIRECTORY:-files}

  hackathon-postgres:
    container_name: hackathon-postgres
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - hackathon-network
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data