# Generated by Django 4.0.4 on 2022-06-30 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teamparticipant',
            name='role',
            field=models.CharField(choices=[('C', 'Captain'), ('T', 'Teammate'), ('I', 'Invited')], default='I', max_length=1),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.team')),
            ],
        ),
    ]
