# Generated by Django 4.0.4 on 2022-07-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_team_url_alter_teamparticipant_role_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teamparticipant',
            name='role',
            field=models.CharField(choices=[('C', 'Captain'), ('T', 'Teammate'), ('I', 'Invited'), ('D', 'Declined')], default='I', max_length=1),
        ),
    ]
