# Generated by Django 4.0.4 on 2022-07-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_team_score_alter_team_url_alter_teamparticipant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='url',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
