# Generated by Django 4.0.4 on 2022-07-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_team_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='labels_csv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='test_py',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='train_py',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
